server:
  port: 8082  # Puerto en el que estará corriendo el Admin Service

spring:
  boot:
    admin:
      context-path: /admin  # Establece un contexto base para el Admin Service
  application:
    name: admin-service
  cloud:
    discovery:
      enabled: true  # Habilita la integración con Eureka para descubrir otros microservicios

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL de tu Eureka Server (Registry Service)
